export const Actiontypes = {
    FETCH_LOGIN_CRED: "FETCH_LOGIN_CRED",
    APP_SIDEBAR_SHOW: "set",
    FETCH_EMP_PROFILE_DATA: "FETCH_EMP_PROFILE_DATA",

    //For the each employee prifile listing in the employee record list
    FETCH_ACADEMIC_DATA: "FETCH_ACADEMIC_DATA",
    FETCH_EXPERIENCE_DATA: "FETCH_EXPERIENCE_DATA",
    FETCH_WAGE_DATA: "FETCH_WAGE_DATA",
    FETCH_LEAVE_DATA: "FETCH_LEAVE_DATA",
    FETCH_EMP_PERSONAL_INFOM: "FETCH_EMP_PERSONAL_INFOM",
    FETCH_DEPT_SHIFT_DATA: "FETCH_DEPT_SHIFT_DATA",
    FETCH_EMP_LEAVE_LIST: "FETCH_EMP_LEAVE_LIST",
    FETCH_DEPARTMENT_LIST: "FETCH_DEPARTMENT_LIST",//department list dropdown
    FETCH_DEPARTSEC_LIST: "FETCH_DEPARTSEC_LIST",//dept section list dropdown
    FETCH_LEAVE_AVAIL_LIST: "FETCH_LEAVE_AVAIL_LIST",
    FETCH_NOTIFYDETL: "FETCH_NOTIFYDETL",

    //For the employee record list in the Employee File From
    FETCH_EMP_RECORD_LIST: "FETCH_EMP_RECORD_LIST",

    //for getting employee details in duty plan
    FETCH_EMP_DETAILS: "FETCH_EMP_DETAILS",
    FETCH_ALERT_MESSAGE: "FETCH_ALERT_MESSAGE",
    FETCH_EMP_MESSAGE: "FETCH_EMP_MESSAGE",
    FETCH_ANNOUNCEMENT_MESSAGE: "FETCH_ANNOUNCEMENT_MESSAGE",
    GET_MODULE_RIGHTS: "GET_MODULE_RIGHTS",
    FETCH_EMP_LEAVE_PROCESS_DETL: "FETCH_EMP_LEAVE_PROCESS_DETL",
    FETCH_EMP_LEAVE_PROCESS_DETL_DEFAULT: "FETCH_EMP_LEAVE_PROCESS_DETL_DEFAULT",
    FETCH_REGION_DATA: "FETCH_REGION_DATA",
    FETCH_PROFFESSIONAL_TAX: "FETCH_PROFFESSIONAL_TAX",
    FETCH_JOB_DESCRIPTION: "FETCH_JOB_DESCRIPTION",
    //for getting employee bloodgroup
    FETCH_EMP_BLOODGROUP: "FETCH_EMP_BLOODGROUP ",
    FETCH_EMP_DEPTSECT: "FETCH_EMP_DEPTSECT ",
    //for getting employee district wise region
    FETCH_EMP_DISTREGION: "FETCH_EMP_DISTREGION",
    //to get employee district
    FETCH_EMP_DISTRICT: "FETCH_EMP_DISTRICT",
    //to get employee name
    FETCH_EMP_NAME: "FETCH_EMP_NAME",
    //to get employee religion
    FETCH_EMP_RELIGION: "FETCH_EMP_RELIGION",
    FETCH_CHANGE_STATE: "FETCH_CHANGE_STATE",
    // to get employee institution type
    FETCH_EMP_INSTITUTION: "FETCH_EMP_INSTITUTION",
    FETCH_EMP_CATEGORY: "FETCH_EMP_CATEGORY",
    FETCH_EMP_DESIGNATION: "FETCH_EMP_DESIGNATION",
    FETCH_EMP_EDUCATION: "FETCH_EMP_EDUCATION",
    FETCH_EMP_COURSE: "FETCH_EMP_COURSE",
    FETCH_EMP_SPECILIZATION: "FETCH_EMP_SPECILIZATION"
}