export const Actiontypes = {
    FETCH_LOGIN_CRED: "FETCH_LOGIN_CRED",
    APP_SIDEBAR_SHOW: "set",
    FETCH_EMP_PROFILE_DATA: "FETCH_EMP_PROFILE_DATA",
    FETCH_ACADEMIC_DATA: "FETCH_ACADEMIC_DATA",
    FETCH_EXPERIENCE_DATA: "FETCH_EXPERIENCE_DATA",
    FETCH_WAGE_DATA: "FETCH_WAGE_DATA",
    FETCH_LEAVE_DATA: "FETCH_LEAVE_DATA",
    FETCH_EMP_RECORD_LIST: "FETCH_EMP_RECORD_LIST",
    FETCH_DEPT_SHIFT_DATA: "FETCH_DEPT_SHIFT_DATA",
    FETCH_EMP_LEAVE_LIST: "FETCH_EMP_LEAVE_LIST"
    FETCH_DEPARTMENT_LIST: "FETCH_DEPARTMENT_LIST",//department list dropdown
    FETCH_DEPARTSEC_LIST: "FETCH_DEPARTSEC_LIST",//dept section list dropdown

}